### ISSUE TITLE
A few unzipping issues

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/zerotoheroes.com#128]
```
StackTrace for exception:
net.lingala.zip4j.exception.ZipException: net.lingala.zip4j.exception.ZipException: net.lingala.zip4j.exception.ZipException: invalid local header signature for file: replay.xml
    at net.lingala.zip4j.unzip.Unzip.initExtractFile(Unzip.java:163)
    at net.lingala.zip4j.unzip.Unzip.extractFile(Unzip.java:117)
    at net.lingala.zip4j.model.FileHeader.extractFile(FileHeader.java:292)
    at net.lingala.zip4j.core.ZipFile.extractFile(ZipFile.java:634)
    at net.lingala.zip4j.core.ZipFile.extractFile(ZipFile.java:587)
    at net.lingala.zip4j.core.ZipFile.extractFile(ZipFile.java:566)
    at com.coach.plugin.hearthstone.HSReplay.transformReplayFile(HSReplay.java:132)
    at com.coach.review.replay.ReplayProcessor.processReplayFile(ReplayProcessor.java:53)
    at com.coach.review.ReviewApiHandler.createReview(ReviewApiHandler.java:359)
    at
```

**Comment by sebastientromp** [comment]
```
Review [id=5aa43271fc30240001bae98c, title=null
, key=null, temporaryKey=hearthstone/replay/2018/3/10/redruby_priest_vs_rogue_1520710258434_5aa43271fc30240001bae98c.hszip, replay=null
, temporaryReplay=false
, fileType=hszip, mediaType=null, reviewType=null
, participantDetails=ParticipantDetails(playerName=null, opponentName=null, playerCategory=null, opponentCategory=null, skillLevel=[Tag(text=casual, type=null)]), metaData=null
, transcodingDone=false
, published=true, visibility=restricted, closedDate=null, helpScore=0.0, debugScore=null, invalidGame=false, lastMetaDataParsingDate=null, claimableAccount=true]
```

**Comment by volth** [comment]
It is reported in 2015 but still not fixed: http://www.lingala.net/zip4j/forum/index.php?topic=410.0

**Comment by sebastientromp** [comment]
Thanks!

The zip file in my case are really small (< 100KB once zipped) so it might be another issue? 
It affects a really small portion of zip files (about 1 for every 100k) so I haven't started looking into it yet.

**Comment by sebastientromp** [comment]
I stopped using zip4j and read the zipped file directly from the InputStream returned by s3, so it should be better now
