### ISSUE TITLE
Issue parsing ArenaDrafts deck

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/zerotoheroes.com#39]
http://www.zerotoheroes.com/r/hearthstone/580e99020ca1360d8d1f57e1/noblehelium-druid-vs-falconx-mage-1926-241016

http://arenadrafts.com/Arena/View/7176edff-f25c-43a7-8e04-5d010faba9d7

```
StackTrace for exception:
org.json.JSONException: JSONObject["Card0Info"] not found.
    at org.json.JSONObject.get(JSONObject.java:473)
    at com.coach.plugin.hearthstone.DeckParser.parseArenaDraftsDeck(DeckParser.java:441)
```

**Comment by sebastientromp** [comment]
Looking at the JSON produced by http://arenadrafts.com/Arena/View/7176edff-f25c-43a7-8e04-5d010faba9d7?format=JSON, it looks like the first pick has "cardpicked: 0", which is not a valid index (should be 1-3)
