### ISSUE TITLE
NPE parsing replay

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/zerotoheroes.com#98]
StackTrace for exception:
java.lang.NullPointerException
    at com.zerotoheroes.hsgameconverter.logparser.ParserState.updateCurrentNode(ParserState.java:50)
    at com.zerotoheroes.hsgameconverter.logparser.handlers.ChoicesHandler.handle(ChoicesHandler.java:63)
    at com.zerotoheroes.hsgameconverter.logparser.ReplayParser.addData(ReplayParser.java:131)
    at com.zerotoheroes.hsgameconverter.logparser.ReplayParser.read(ReplayParser.java:111) Show more…
Exception during plugin execution
com.coach.plugin.hearthstone.HSReplay
Review [id=null, title=null
, author=인성좋은유저, authorId=5982dc8df5b80006f518ba0d
, uploaderApplicationKey=null, uploaderToken=null
, key=null, temporaryKey=hearthstone/replay/2017/8/3/1501748451384-ss.txt,

**Comment by sebastientromp** [comment]
Log file is missing the game creation part
